const seedData = [
  // MEALS - Chinese Veg
  {
    superCategory: 'Meals',
    subCategory: 'Chinese Veg',
    name: 'Manchurian',
    description: 'Crispy vegetable balls tossed in a tangy, spicy sauce. Available Dry or Gravy.',
    price: 180,
    veg: true,
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Meals',
    subCategory: 'Chinese Veg',
    name: 'Paneer Manchurian',
    description: 'Soft paneer cubes in a rich Manchurian sauce. Available Dry or Gravy.',
    price: 200,
    veg: true,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Meals',
    subCategory: 'Chinese Veg',
    name: 'Paneer Chilli',
    description: 'Juicy paneer tossed with bell peppers and chilli sauce. Available Dry or Gravy.',
    price: 250,
    veg: true,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Meals',
    subCategory: 'Chinese Veg',
    name: 'Honey Chilli Potato',
    description: 'Crispy potato strips glazed with honey chilli sauce — sweet, spicy & addictive.',
    price: 150,
    veg: true,
    image: 'https://images.unsplash.com/photo-1518013431117-eb1465fa5752?w=400&auto=format&fit=crop',
    available: true,
  },
  // MEALS - Rice
  {
    superCategory: 'Meals',
    subCategory: 'Rice',
    name: 'Veg Fried Rice',
    description: 'Wok-tossed rice with fresh vegetables and fragrant seasoning.',
    price: 200,
    veg: true,
    image: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Meals',
    subCategory: 'Rice',
    name: 'Paneer Fried Rice',
    description: 'Classic fried rice elevated with fresh paneer cubes and aromatic spices.',
    price: 250,
    veg: true,
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Meals',
    subCategory: 'Rice',
    name: 'Schezwan Fried Rice',
    description: 'Bold, fiery Schezwan sauce meets perfectly fried rice for a spicy treat.',
    price: 280,
    veg: true,
    image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400&auto=format&fit=crop',
    available: true,
  },
  // SNACKS - Pasta
  {
    superCategory: 'Snacks',
    subCategory: 'Pasta',
    name: 'Veg Macaroni',
    description: 'Classic macaroni pasta tossed with seasonal vegetables and rich sauce.',
    price: 180,
    veg: true,
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Snacks',
    subCategory: 'Pasta',
    name: 'Red Sauce Pasta',
    description: 'Al dente pasta smothered in a rich, tangy tomato-based Arrabbiata sauce.',
    price: 210,
    veg: true,
    image: 'https://images.unsplash.com/photo-1598866594230-a7c12756260f?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Snacks',
    subCategory: 'Pasta',
    name: 'White Sauce Pasta',
    description: 'Creamy béchamel pasta with herbs — comforting and indulgent.',
    price: 250,
    veg: true,
    image: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Snacks',
    subCategory: 'Pasta',
    name: 'Wheat Pasta',
    description: 'Healthy whole wheat pasta packed with nutrition and fresh garden vegetables.',
    price: 300,
    veg: true,
    image: 'https://images.unsplash.com/photo-1473093226555-0ac86d0d4010?w=400&auto=format&fit=crop',
    available: true,
  },
  // SNACKS - Maggi
  {
    superCategory: 'Snacks',
    subCategory: 'Maggi',
    name: 'Veg Maggi',
    description: "Everyone's favourite — classic Maggi noodles with fresh vegetables.",
    price: 60,
    veg: true,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Snacks',
    subCategory: 'Maggi',
    name: 'Paneer Maggi',
    description: 'Creamy Maggi noodles loaded with soft paneer cubes and spices.',
    price: 70,
    veg: true,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Snacks',
    subCategory: 'Maggi',
    name: 'Cheese Corn Maggi',
    description: 'Gooey cheese meets sweet corn in this irresistible Maggi twist.',
    price: 60,
    veg: true,
    image: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Snacks',
    subCategory: 'Maggi',
    name: 'Soup Maggi',
    description: 'Warm, soupy Maggi noodles in a comforting broth — perfect for cold days.',
    price: 50,
    veg: true,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&auto=format&fit=crop',
    available: true,
  },
  // SNACKS - Momos
  {
    superCategory: 'Snacks',
    subCategory: 'Momos',
    name: 'Steam Veg Momos (8 pcs)',
    description: 'Steamed dumplings packed with seasoned vegetables, served with chutney.',
    price: 50,
    veg: true,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Snacks',
    subCategory: 'Momos',
    name: 'Steam Paneer Momos (8 pcs)',
    description: 'Delicate steamed dumplings filled with spiced paneer and herbs.',
    price: 70,
    veg: true,
    image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Snacks',
    subCategory: 'Momos',
    name: 'Soup Momos (6 pcs)',
    description: 'Momos served in a flavorful, aromatic soup broth — warming and satisfying.',
    price: 80,
    veg: true,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Snacks',
    subCategory: 'Momos',
    name: 'Jhol Momos (6 pcs)',
    description: 'Nepali-style momos bathed in a spicy, tangy jhol achar sauce.',
    price: 100,
    veg: true,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Snacks',
    subCategory: 'Momos',
    name: 'Afghani Momos (6 pcs)',
    description: 'Momos in a rich, creamy white Afghani sauce — truly indulgent.',
    price: 120,
    veg: true,
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&auto=format&fit=crop',
    available: true,
  },
  // SNACKS - Burger
  {
    superCategory: 'Snacks',
    subCategory: 'Burger',
    name: 'Aloo Tikki Burger',
    description: 'Crispy spiced potato tikki in a soft bun with fresh veggies and chutney.',
    price: 90,
    veg: true,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Snacks',
    subCategory: 'Burger',
    name: 'Paneer Burger',
    description: 'Grilled paneer patty topped with fresh veggies and secret café sauce.',
    price: 120,
    veg: true,
    image: 'https://images.unsplash.com/photo-1550317138-10000687a72b?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Snacks',
    subCategory: 'Burger',
    name: 'Cheese Burger',
    description: 'Double cheese slices melt over a crispy patty — pure cheesy bliss.',
    price: 120,
    veg: true,
    image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Snacks',
    subCategory: 'Burger',
    name: 'Schezwan Cheese Burger',
    description: 'A fiery Schezwan kick topped with melted cheese — for the brave ones.',
    price: 150,
    veg: true,
    image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400&auto=format&fit=crop',
    available: true,
  },
  // BEVERAGES - Drinks
  {
    superCategory: 'Beverages',
    subCategory: 'Drinks',
    name: 'Cold Coffee',
    description: 'Rich, frothy cold coffee blended to café perfection.',
    price: 120,
    veg: true,
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Beverages',
    subCategory: 'Drinks',
    name: 'Cold Coffee with Ice Cream',
    description: 'Classic cold coffee crowned with a generous scoop of vanilla ice cream.',
    price: 150,
    veg: true,
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Beverages',
    subCategory: 'Drinks',
    name: 'Oreo Shake',
    description: 'Thick, dreamy milkshake blended with crushed Oreo cookies.',
    price: 100,
    veg: true,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Beverages',
    subCategory: 'Drinks',
    name: 'KitKat Shake',
    description: 'Indulgent chocolate milkshake blended with crunchy KitKat bars.',
    price: 100,
    veg: true,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Beverages',
    subCategory: 'Drinks',
    name: 'Chocolate Shake',
    description: 'Pure chocolate bliss — thick, creamy and deeply satisfying.',
    price: 100,
    veg: true,
    image: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Beverages',
    subCategory: 'Drinks',
    name: 'Mango Shake',
    description: 'Real Alphonso mango blended into a thick, refreshing summer shake.',
    price: 90,
    veg: true,
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Beverages',
    subCategory: 'Drinks',
    name: 'Mix Fruit Shake',
    description: 'A vibrant blend of seasonal fresh fruits into one refreshing glass.',
    price: 150,
    veg: true,
    image: 'https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Beverages',
    subCategory: 'Drinks',
    name: 'Strawberry Shake',
    description: 'Sweet, pink, and luscious — a classic strawberry milkshake.',
    price: 100,
    veg: true,
    image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&auto=format&fit=crop',
    available: true,
  },
  // SALAD & SOUP
  {
    superCategory: 'Salad & Soup',
    subCategory: 'Salad',
    name: 'Garden Fresh Salad',
    description: 'Crisp lettuce, cucumber, tomatoes, olives and bell peppers in a light vinaigrette.',
    price: 120,
    veg: true,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Salad & Soup',
    subCategory: 'Salad',
    name: 'Paneer Tikka Salad',
    description: 'Grilled spiced paneer over fresh greens with mint-lime dressing.',
    price: 160,
    veg: true,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Salad & Soup',
    subCategory: 'Salad',
    name: 'Russian Salad',
    description: 'Classic Russian salad with boiled vegetables, peas and creamy dressing.',
    price: 140,
    veg: true,
    image: 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Salad & Soup',
    subCategory: 'Soup',
    name: 'Sweet Corn Soup',
    description: 'Creamy, comforting sweet corn soup with a hint of pepper and herbs.',
    price: 80,
    veg: true,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Salad & Soup',
    subCategory: 'Soup',
    name: 'Tomato Soup',
    description: 'Rich, velvety tomato soup with fresh basil and a swirl of cream.',
    price: 90,
    veg: true,
    image: 'https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?w=400&auto=format&fit=crop',
    available: true,
  },
  {
    superCategory: 'Salad & Soup',
    subCategory: 'Soup',
    name: 'Manchow Soup',
    description: 'Thick, spicy Indo-Chinese soup loaded with vegetables and crispy noodles on top.',
    price: 100,
    veg: true,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&auto=format&fit=crop',
    available: true,
  },
];

module.exports = seedData;
